apiVersion: v1
kind: Secret
metadata:
  name: horilla-secrets
  namespace: dev
type: Opaque
data:
  # Connection string: postgres://horilla:horilla@postgres:5432/horilla
  database-url: cG9zdGdyZXM6Ly9ob3JpbGxhOmhvcmlsbGFAcG9zdGdyZXM6NTQzMi9ob3JpbGxh
