apiVersion: apps/v1
kind: Deployment
metadata:
  name: horilla-app
  labels:
    app: horilla
spec:
  replicas: 2
  selector:
    matchLabels:
      app: horilla
  template:
    metadata:
      labels:
        app: horilla
    spec:
      containers:
      - name: horilla-app
        image: arunkumarravi08/horilla-app:latest # Jenkins will update this tag
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: "postgres://postgres:postgres@horilla-db:5432/horilla"
---
apiVersion: v1
kind: Service
metadata:
  name: horilla-service
spec:
  type: LoadBalancer
  selector:
    app: horilla
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
